theme =  "monokai"

[editor]
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics",
         "selections",
         "position",
         "spacer",
         "position-percentage",
         "file-encoding",
         "file-line-ending",
         "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
y = "yank_joined_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
C-s = ":write-all"
C-j = "save_selection"

[keys.select]
p = ":clipboard-paste-replace"
y = "yank_joined_to_clipboard"
